### ISSUE TITLE
customer

### ISSUE THREAD

**Issue by atkaksoy501** [atkaksoy501/TurkcellCRM#1]
individualCustomer
corporateCustomer 
şeklinde iki müşteri tipini de desteklemesi gerekiyor. Bunların üstünde de base görevi görecek bir customer entity olacak. rentacar projesindeki gibi.

**Comment by atkaksoy501** [comment]
customer tablosunun içine contact tablosundakileri koyalım. contact diye ayrı bir entity/tablo olmasın.

**Comment by atkaksoy501** [comment]
AccountAddress
Address

tabloları ayrı olacak
AccountAddress, Account ile Address ara tablosu olacak

**Comment by atkaksoy501** [comment]
AccountTypes adında referans tablosu oluşturulacak enum görevi görecek
Account içinde type_id şeklinde tanımlanacak

**Comment by atkaksoy501** [comment]
Offer tablosu olacak kişiye özel teklifler için

**Comment by atkaksoy501** [comment]
tablolar çoğul isimlendirilecek

**Comment by canertas1** [comment]
corparate customera şuan için gerek yok

**Comment by canertas1** [comment]
gender kısmı veri tablosunda enum olarak ve sayı olarak kaydolcak

**Comment by atkaksoy501** [comment]
> invidualcustomer kısmında gender için veri tablosunda enum olarak ve sayı olarak kaydolcak

abi kesinlikle bence enumları sayı olarak tutmamalıyız. enumları char olarak 'F' veya 'M' diye kaydetmeliyiz bence daha şık. hoca sayı dedi ama bence bu daha şık

**Comment by canertas1** [comment]
individual customer kısmında id ısmı  customerid oarak tutulcak ve  bu hem pk hemde fk olacak

**Comment by atkaksoy501** [comment]
https://github.com/engindemirog/inventory.service
https://github.com/engindemirog/filter.service3
kafka dockera kurulacak
